{block #title}Projekt – {$project->name}{/block}


{block #content}
<h1>{include #title}</h1>
<p>Žadatel: {$project->applicant} | Grantové kolo: <a href="{link Homepage:round, $round->id}">{$round->name}</a>
{if trim($project->otherLinks) != ''}
	{? $otherLinks = explode("\n", $project->otherLinks)}
	
	 <br>Přílohy: 
	{foreach $otherLinks as $link}
		{? $pathInfo = pathinfo(trim($link))}
		<a href="{=trim($link)}">{$pathInfo['basename']}</a>{if !$iterator->isLast()},{/if}
	{/foreach}
{/if}
</p>

<iframe src="{=trim($project->applicationLink)}" style="width: 760px; height: 500px"></iframe>


{if $round->phase == 'firstRating' OR $round->phase == 'secondRating'}	
	{if $user->isAllowed('project', 'rate')}
		<h2>Hodnotit projekt
			{if $round->phase == 'firstRating'}(poprvé, před diskusí){/if}
			{if $round->phase == 'secondRating'}(podruhé, po diskusi){/if}
		</h2>

		{control rateProjectForm begin}
		{control rateProjectForm errors}

		{var form => $control['rateProjectForm']}	
		{var ratingsValues = $project->getRatings($round->phase, $user->getId())}
		{var eligibilityValues = $project->getEligibility($round->phase, $user->getId())}
		{if $ratingsValues}{? $form->setValues($ratingsValues)}{/if}
		{if $eligibilityValues}
			{? $form['notEligible']->setValue($eligibilityValues->notEligible)}
			{? $form['reasons']->setValue($eligibilityValues->reasons)}
		{/if}
		<table>

	
		<tr>
		{foreach $form->components as $itemId => $item}
			{if $itemId > 0}
				<td style="width: 33%; vertical-align: top;"><strong>{$item->label}</strong><br>
					{$item->control}<br>
					<span style="margin-top: 1em; display: block; line-height: 1.2em">{$item->getOption('description')}</span></td>
			
			{if $iterator->getCounter()%3 == 0}</tr><tr>{/if}
			{/if}
		{/foreach}
		</tr>
		</table>
		<p>{$form['notEligible']->control} {$form['notEligible']->label}</p>
		<p id="eligibility">{$form['reasons']->label}<br>{$form['reasons']->control} </p>
		<p>{$form['submit']->control}</p>
	
		{control rateProjectForm end}
		</div>
	{else}
		<p>Právě probíhá fáze „{$round->getPhaseName()}“. Informace budou zveřejněny po skončení této fáze.</p>
	{/if}
{elseif $round->phase == 'deliberation'}
	<h2>Výsledky prvního hodnocení</h2>
	<p>Jednotlivá hodnocení jsou po prvním kole promíchána. Porotci si v diskusi mohou ponechat svá hodnocení
		pro sebe anebo vyjít s vlastním hodnocením veřejně. Oba postupy mohou přinést pozitivní výsledky.
		Po fázi druhého hodnocení budou konkrétní výsledky z obou kol přiřazeny k porotcům.</p>
	<table>
		<tr><th>Kategorie</th><th>Jednotlivá hodnocení</th><th>Průměr</th></tr>
		{var count = 0}
		{var total = 0}
		{foreach $categories as $id => $category}
			<tr>
				<th title="{$category->description}">{$category->name}</th>
				{? shuffle($ratings[$category->id])}
				<td>{foreach $ratings[$category->id] as $rating}<span class="ratingNum{$rating}">{$rating}</span>{if !$iterator->isLast()}, {/if}{/foreach}</td>
				<td>{=array_sum($ratings[$category->id])/count($ratings[$category->id])}</td>
			</tr>
		{? $count++; $total += array_sum($ratings[$category->id])/count($ratings[$category->id])}	
		{/foreach}
		<tr><th colspan="2">Celkové hodnocení (průměr)</th><th>{=$total/$count}</th></tr>
	</table>
	
	<h2>Doporučení k podpoře a komentáře komise</h2>
	<p>Porotci hodnotí projekty podle několika kritérií a podle těchto hodnocení jsou projekty
		řazeny při výběru těch, které budou podpořeny. Nicméně, pokud jim na projektu něco nesedí,
		mohou projekt <strong>nedoporučit k podpoře</strong> – tím říkají, že je v návrhu projektu
		něco zásadního špatně. Pokud projekt získá dvě a více <strong>nedoporučení</strong>, přesouvá
		se automaticky „pod čáru“. V prvním kole má toto hodnocení orientační charakter (a hodnocení
		jsou anonymní), ve druhém je rozhodující.</p>
		
	<table>
		{dump $eligibility}
		{foreach $eligibility as $el}
			<tr><td>
				{!= $el->notEligible == 0 ? 'doporučeno' : '<strong>nedoporučeno</strong>'}				
			</td><td>
				{!= trim($el->reasons) == '' ? 'bez komentáře' : nl2br($el->reasons)}				
			</td></tr>
		{/foreach}
	</table>	
		
{elseif $round->phase == 'results'}
	<h2>Konečné výsledky z obou hodnocení</h2>

	{dump $jurors}
	<table>
		<tr>
			<th>Kategorie</th>
			{foreach $jurors as $juror}<th>{$juror->name}</th>{/foreach}
			<th>Průměry</th>
			<th>Výsledek</th>			
		</tr>
		{var count = array('firstRating' => 0, 'secondRating' => 0)}
		{var total = array('firstRating' => 0, 'secondRating' => 0)}
		{foreach $categories as $id => $category}
			<tr>
				<th title="{$category->description}">{$category->name}</th>
				
				{if !isset($firstRatings[$category->id])}
					<td colspan="{=count($jurors)+2}">V této kategorii nikdo nehodnotil v prvním hodnocení.</td>
					{? continue; }
				{/if}
				{if !isset($secondRatings[$category->id])}
					<td colspan="{=count($jurors)+2}">V této kategorii nikdo nehodnotil ve druhém hodnocení.</td>
					{? continue; }
				{/if}
				
				{foreach $jurors as $juror}
					
					{var firstRating = isset($firstRatings[$category->id][$juror->id]) ?
						$firstRatings[$category->id][$juror->id] : '—' }
					{var secondRating = isset($secondRatings[$category->id][$juror->id]) ?
						$secondRatings[$category->id][$juror->id] : '—' }	
					<td>						
						<span class="ratingNum{$firstRating}">{$firstRating}</span> |
						<span class="ratingNum{$secondRating}">{$secondRating}</span>
					</td>
				
				{/foreach}
				<td>
					{=array_sum($firstRatings[$category->id])/count($firstRatings[$category->id])} | 
					{=array_sum($secondRatings[$category->id])/count($secondRatings[$category->id])}					
				</td>
				<td>
					<strong>{=(array_sum($firstRatings[$category->id])/count($firstRatings[$category->id])
						+ array_sum($secondRatings[$category->id])/count($secondRatings[$category->id]))/2}</strong>
				</td>
			</tr>
		{? 	$count['firstRating']++;  
			$total['firstRating'] += array_sum($firstRatings[$category->id])/count($firstRatings[$category->id]);
		}

		{?	$count['secondRating']++;
			$total['secondRating'] += array_sum($secondRatings[$category->id])/count($secondRatings[$category->id]);
		}	
		{/foreach}
		<tr><th colspan="{=count($jurors)+1}">Celkové hodnocení (průměr)</th>
		{if $count['firstRating'] == 0 OR $count['secondRating'] == 0}
			<th>&ndash;</th><th>&ndash;</th>
		{else}	
			<th>
				{=$total['firstRating']/$count['firstRating']} | {=$total['secondRating']/$count['secondRating']}
			</th>
			<th>
				{=($total['firstRating']/$count['firstRating'] + $total['secondRating']/$count['secondRating'])/2}
			</th>
		{/if}
		</tr>
	</table>	
	
{/if}