{block #title}{$round->name}{/block}


{block #content}
<h1>Projektové kolo: {include #title}</h1>
<p>Právě probíhá fáze <strong>{$round->getPhaseName()}</strong>.</p>


<h2>Předložené projekty</h2>
{if !count($projects)} 

<p class="blank">Zatím žádné projekty</p>

{else}
	<table>
		<tr>
			<th>Název projektu</th>
			<th>1. hodnocení</th>
			<th>2. hodnocení</th>
			<th>Celkem</th>
		</tr>
		{foreach $projects as $project}
			<tr {if $iterator->isOdd()}class="odd"{/if}>
				<td><a href="{link Homepage:project, $project->id}">{$project->name}</a><br>{$project->applicant}</td>
				<td>
					{if $round->phase == 'firstRating'}
						{var $ratingCount = isset($ratingCounts[$project->id]) ? $ratingCounts[$project->id] : 0}
						{if $ratingCount}Již hodnotilo<br> {$ratingCount} z 5 porotců.{else}Zatím nehodnoceno.{/if}
					{/if}
					
					
				</td>
				<td></td>
				<td></td>
			</tr>
		
			{* vloženo {$round->createdDATE|date: "%e. %B %Y"} *}
	
		{/foreach}
	</table>
{/if}




{if $user->isAllowed('round', 'edit')}

	<hr>
	
	<h2>Vložit projekt</h2>
	{control editProjectForm}
{/if}