{block #title}{$round->name}{/block}

{block #firstRatingRules}
<ol><li>V první fázi členové Komise hodnotí žádosti  podle Kritérií hodnocení pro dané stipendijní kolo.
</li><li>Hodnocení jednotlivých kritérií provádí komisař na pětistupňové škále. Nejlepším hodnocením je pět hvězdiček, nejhorším jedna hvězdička.
</li><li>Komisař se též může rozhodnout, že neudělí žádnou hvězdičku, ale označí žádost jako “nevhodnou k podpoře”.
</li><li>Pokud žádost získá alespoň od dvou komisařů hodnocení “nevhodné k podpoře”, nebude podpořena.
</li><li>První fáze je uskutečňována prostřednictvím pomocného software.
</li><li>První fáze musí být ukončena nejpozději 10 pracovních dnů po uzávěrce daného stipendijního kola.
</li><li>Předseda ve spolupráci se SK neprodleně zveřejní výsledky hodnocení. Součástí zveřejnění jsou plná znění žádostí o stipendium a jejich průběžné pořadí. Dokumenty jsou zveřejněny ve formátu PDF.
</li><li>Hlasování jednotlivých hodnotitelů jsou anonymizována, aby nebylo možné určit, který člen Komise jak hodnotil.</li></ol>
{/block}

{block #secondRatingRules}
<ol>
<li>Ve druhé fázi hodnocení Komise podruhé hodnotí žádosti s přihlédnutím na průběh diskuse.
</li><li>Ve druhé fázi platí stejná pravidla hodnocení jako v první fázi (dle §8, odst. 2–5).
</li><li>Pokud žádost získá alespoň od dvou komisařů ve druhé fázi hodnocení “nevhodné k podpoře”, nebude podpořena.
</li><li>Konečné pořadí žádostí je stanoveno podle průměrného hodnocení z obou kol hodnocení.
</li><li>Výsledkem práce Komise je řazený Seznam žádostí (dále jen Seznam), které mají být v tomto pořadí podpořeny. Seznam je řazen sestupně.
</li><li>Žádosti, které byly vyřazeny pro nesplnění formálních požadavků jsou takto v Seznamu označeny.
</li><li>Žádosti, které dle názoru Komise nejsou vhodné k podpoře, jsou v Seznamu	označeny “nevhodné k podpoře”.
</li><li>Pokud je žádost neúspěšná, může žadatel znovu zažádat maximálně jednou. V případě, že žádost bude Komisí znovu zamítnuta, nelze již na stejný projekt žádost podat.
</li><li>Podporu získává každá žádost v Seznamu, dokud nejsou vyčerpány přidělené	prostředky na dané stipendijní kolo. Prostředky nemůže získat žádost, která je 	označena jako “nevhodná k podpoře”.
</li><li>Předseda komise předá Seznam do tří dnů zástupcům SK.
</li><li>Studentská komora předá Seznam pověřenému proděkanovi do pěti dnů poté, co jej obdrží od předsedy Komise. Proděkan na základě tohoto Seznamu rozhodne o udělení stipendií.	</li>
</ol>
{/block}


{block #preparation}
	<p>Předseda komise právě plní systém žádostmi žadatelů. Zatím neprobíhá hlasování.</p>
{/block}
{block #firstRating}<p>Právě probíhá první hlasování podle následujících pravidel.</p>{include #firstRatingRules}{/block}
{block #deliberation}<p>První hlasování skončilo, <strong>{$round->deliberationTimePlace} se koná setkání
	Komise se žadateli a celou akademickou obcí fakulty.</strong>
	Hlasování proběhlo podle následujících pravidel:</p>{include #firstRatingRules}{/block}
{block #secondRating}<p>Právě probíhá druhé hlasování podle následujících pravidel.</p>{include #secondRatingRules}{/block}
{block #results}Druhé hlasování skončilo a níže vidíte konečné výsledky.
Hlasování proběhlo podle následujících pravidel:</p>{include #secondRatingRules}{/block}

{block #category}
	<li><strong>{$category->name}</strong>
	{if $user->isAllowed('round', 'edit') AND $round->phase == 'preparation'
		AND isset($removable)}
		<a href="{link unlinkRatingCategory!, categoryID => $category->id}">odebrat (v tomto projektovém kole)</a>
	{/if}
	<br>
	{$category->description}</li>
{/block}

{block #ratingCategories}

	<h2>Kritéria hodnocení</h2>
	<ul class="ratingCategories">
	{foreach $currentCategories as $category}
		{include #category, category => $category, removable => true}
	{/foreach}
	</ul>

	{if $user->isAllowed('round', 'edit') AND $round->phase == 'preparation'}

		<p>Kritéria hodnocení můžete buď převzít z minulého kola anebo vložit zcela nová
		(přenesená kritéria můžete případně odebrat a doplnit o nová).</p>

		<h3 class="collapsibleForm">1. <a href="#">Přenést kritéria z minulého kola</a></h3>
		{var form = $control['cloneRatingCategoriesForm']}
		{control cloneRatingCategoriesForm begin}
		{control cloneRatingCategoriesForm errors}
			<ul class="ratingCategories">
			{foreach $previousCategories as $category}
				{include #category, category => $category}
			{/foreach}
			</ul>

			{$form['submit']->control}
		{control cloneRatingCategoriesForm end}

		<h3 class="collapsibleForm">2. <a href="#">Vložit zcela nová kritéria</a></h3>
		{control addRatingCategoriesForm}

	{/if}
{/block}


{block #content}
<h1>Projektové kolo: {include #title}</h1>
<p>Právě probíhá fáze <strong>{$round->getPhaseName()}</strong>.</p>

{if $round->phase == 'preparation'}{include #preparation}{/if}
{if $round->phase == 'firstRating'}{include #firstRating}{/if}
{if $round->phase == 'deliberation'}{include #deliberation, round => $round}{/if}
{if $round->phase == 'secondRating'}{include #secondRating}{/if}
{if $round->phase == 'results'}{include #results}{/if}

{include #ratingCategories}


<h2>Předložené projekty</h2>
{if !count($projects)}

<p class="blank">Zatím žádné projekty</p>

{else}
	<table>
		<tr>
			<th>Název projektu</th>
			<th>1. hodnocení</th>
			<th>2. hodnocení</th>
			<th>Celkem</th>
		</tr>

		{var total = 0}
		{var granted = 0}

		{foreach $projects as $project}
			{if $round->phase == 'deliberation' OR $round->phase == 'results'}
				{var ineligible = FALSE}
				{var noResources = FALSE}

				{if ($round->phase == 'deliberation' AND $project->firstRatingIneligibilityBool)
					OR ($round->phase == 'results' AND $project->secondRatingIneligibilityBool)}
					{var ineligible = TRUE}
				{/if}
				{if $granted + $project->negotiatedAmount > $round->amount}
					{var noResources = TRUE}
				{/if}


				{if !$noResources AND !$ineligible}{? $granted += $project->negotiatedAmount}{/if}
			{? $total += $project->negotiatedAmount}
			{/if}



			<tr {if $iterator->isOdd()}class="odd"{/if}>
				<td><a href="{link Homepage:project, $project->id}">{$project->name}</a>
					<br>{$project->applicant} &bull; {$project->negotiatedAmount}&nbsp;Kč
					{if $project->amount != $project->negotiatedAmount}(sníženo z {$project->amount}&nbsp;Kč){/if}</td>


				<td>
					{if $round->phase == 'firstRating'}
						{var $ratingCount = isset($ratingCounts[$project->id]) ? $ratingCounts[$project->id] : 0}
						{if $ratingCount}Již hodnotilo<br> {=number_format($ratingCount, 0)} z 5
						porotců{if isset($myRating[$project->id])}<br><span class="flag granted">včetně mě</a>{/if}.
						{else}Zatím nehodnoceno.{/if}
					{elseif $round->phase == 'secondRating'}Hodnocení skryto.
					{elseif $round->phase == 'deliberation' OR $round->phase == 'results'}
						{=number_format($project->firstRating, 3, ',', ' ')}

						{if $project->firstRatingIneligibility > 0}
							<span class="flag ineligible" title="Projekt byl {$project->firstRatingIneligibility}x označen jako nevhodný k podpoře.">{$project->firstRatingIneligibility}!</span>
						{/if}

						{if $round->phase == 'deliberation'}
							{if !$noResources AND !$ineligible}
								<span class="flagBox granted"><strong>Předběžně</strong> vyjádřena podpora
										</span>
							{elseif $ineligible}
								<span class="flagBox ineligible"><strong>Předběžně</strong> vyjádřeno nedoporučení</span>
							{else}
								<span class="flagBox noResources"><strong>Předběžně</strong> nemožné podpořit pro nedostatek peněz</span>
							{/if}
						{/if}
					{/if}


				</td>

				<td>
					{if $round->phase == 'secondRating'}
						{var $ratingCount = isset($ratingCounts[$project->id]) ? $ratingCounts[$project->id] : 0}
						{if $ratingCount}Již hodnotilo<br> {=number_format($ratingCount, 0)} z 5
						porotců{if isset($myRating[$project->id])}<br><span class="flag granted">včetně mě</a>{/if}.
						{else}Zatím nehodnoceno.{/if}
					{elseif $round->phase == 'results'}
						{=number_format($project->secondRating, 3, ',', ' ')}

						{if $project->secondRatingIneligibility > 0}
							<span class="flag ineligible" title="Projekt byl {$project->secondRatingIneligibility}x označen jako nevhodný k podpoře.">{$project->secondRatingIneligibility}!</span>
						{/if}
					{/if}
				</td>
				<td>{if $round->phase == 'results'}
						<strong>{=number_format($project->avgRating, 3, ',', ' ')}</strong><br>
						{if !$noResources AND !$ineligible}
							<span class="flagBox granted">Podpořeno
									</span>
						{elseif $ineligible}
							<span class="flagBox ineligible">Nedoporučeno</span>
						{else}
							<span class="flagBox noResources">Nepodpořeno <br>pro vyčerpání peněz</span>
						{/if}
					{/if}</td>
			</tr>


			{* vloženo {$round->createdDATE|date: "%e. %B %Y"} *}

		{/foreach}
		<tr><th colspan="4" style="border-top: 1px solid black;">
			Celková žádaná částka je {=number_format($total, 0, ',', ' ')} Kč.<br>
			Celkem je rozdělováno v projektovém kole {=number_format($round->amount, 0, ',', ' ')} Kč.<br>
			{if $round->phase == 'deliberation'}Celkem by podle prvního kola bylo rozděleno {=number_format($granted, 0, ',', ' ')} Kč{/if}
			{if $round->phase == 'results'}Celkem bylo rozděleno {=number_format($granted, 0, ',', ' ')} Kč.{/if}
			</th></tr>
	</table>
{/if}


{if $round->phase == 'deliberation'}
{* CHART IS NOT OPTIMIZED! *}

<h2>Graf podílu jednotlivých kategorií na celkovém hodnocení</h2>
<p>Poznámka: V grafu jsou jednotlivé kategorie uváděny jako součet, nikoli jako aritmetický průměr.</p>

{var ratingCategories = $round->getRatingCategories('firstRating')}
{var ratings = $round->getProjectsRating('firstRating')}
{? $projects = $projects->fetchAssoc('id')}

<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
  google.load("visualization", "1", {l}packages:["corechart"]{r});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = new google.visualization.DataTable();
	data.addColumn('string', 'Projekt');
	{foreach $ratingCategories as $category}
		data.addColumn('number', '{!$category->name}');
	{/foreach}

    data.addRows([
	 {foreach $ratings as $id => $projectRating}
      ['{!= isset($projects[$id]->name) ? $projects[$id]->name : ''}', {foreach $projectRating as $rating}{!$rating->avgRating}{if !$iterator->isLast()}, {/if}{/foreach}]{if !$iterator->isLast()}, {/if}
	 {/foreach}
    ]);

    var options = {
	  isStacked: true,
	chartArea: {l}top: '30', bottom: '20', height: '85%', width: '400'{r}
      /*title: 'Podíl kategorií na výsledném hodnocení',*/
      /*vAxis: {l}title: 'Projekt',  titleTextStyle: {l}color: 'black'{r}{r}*/
    };

    var chart = new google.visualization.BarChart(document.getElementById('chart_round'));
    chart.draw(data, options);
  }
</script>

<div class="chart" id="chart_round" style="height: 500px;"></div>
{/if}


{if $user->isAllowed('round', 'edit') AND $round->phase == 'preparation'}

	<hr>

	<h2>Vložit projekt</h2>
	{control editProjectForm}
{/if}